script: "bundle exec rspec"
bundler_args: "--binstubs --without documentation"
language: ruby
services: mongodb
before_install: "gem install bundler"
before_script:
  - "bundle exec rake db:migrate RAILS_ENV=test "
rvm:
  - 2.1.0
env:
  - RAILS_VERSION=4.0.4
